[project]
name = "code"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/home/runner/workspace/code/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Advanced-blockchain-powered-document-verification-and-custody-solution]
path = "contracts/Advanced-blockchain-powered-document-verification-and-custody-solution.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
